# Generated by Django 3.0.6 on 2020-05-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fullname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
